### ISSUE TITLE
Compile error after release failure_derive-0.1.2

### ISSUE THREAD

**Issue by aleksuss** [rust-lang-nursery/failure#234]
```
error[E0433]: failed to resolve. Could not find `_core` in `failure`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/error.rs:6:17
  |
6 | #[derive(Debug, Fail)]
  |                 ^^^^ Could not find `_core` in `failure`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `criterion`.
```

**Comment by ensch** [comment]
You are using _failure_derive_ 1.2 with _failure_ <1.2. That is not supported.

Add this tempoarily to your _Cargo.toml_ to make _cargo_ tell you why it is using on older version of _failure_:
```
[dependencies]
failure = "=0.1.2"
```

Add something like this to your _Cargo.toml_ to to make it work until the offending crate with a hard dependency on an older version of failure is fixed:
```
[dependencies]
failure_derive = "=0.1.1"
```

**Comment by dekellum** [comment]
Shouldn't failure_derive 0.1.2 have specified its failure dependency as "^0.1.2" (meaning ">=0.1.2, <0.2.0" then)?

**Comment by ensch** [comment]
I don't think that is possible. _failure_ depends on _failure_derive_, so _failure_derive_ can not depend on _failure_, without causing a dependency loop.

**Comment by ensch** [comment]
The proper solution would probably be for any _failure_ version 0.1.x to have a "=0.1.x" dependency on _failure_derive_. I can't see a reason why one would want to use non-matching versions of _failure_ and _failure_derive_. The are basically the same crate anyway. I think there are only split because there are some restrictions for derive macros in Rust.

**Comment by dekellum** [comment]
Ok, I see on crates.io, *failure* "^0.1.0" shows up as a dev dependency of *failure_derive*, not a normal dependency.

In the other direction *failure* has *failure_derive* as normal (but optional) dependency at "^0.1.2", which presumably allows a patch release of *failure_derive* for bug fixes without needing to also release *failure*.  

Hi @aleksuss, it would be interesting to see the `cargo tree` output or other details of a real world project's dependency graph that exhibits this problem, though. I'm just looking for possible mitigation either here or in my own project that depends on *failure*.

**Comment by Brooooooklyn** [comment]
I can not start a new project which is depending on [actix-web](https://github.com/actix/actix-web), just because it's depending on `failure: 0.1.1`

**Comment by ensch** [comment]
@Brooooooklyn You also can not read, because the proper workaround to your problem has already been posted. 

```
[dependencies]
failure_derive = "=0.1.1"
```

The master branch of actix-web also already has a fix, so you can just use that instead.

**Comment by dgriffen** [comment]
If failure_derive is meant to be used with an exact version of failure then the dependency should definitely be changed to an exact equality to prevent this error in the future. Right now failure 0.1.2 depends on failure_derive ^0.1.2 so if 0.1.3 is released and someone has a hard =0.1.2 in their crate this will break again. That or failure_derive should have a major version bump since it was a breaking change.

**Comment by dekellum** [comment]
There was some reluctance to release the last as 0.2.0, as best I can tell, out of fear that this would result in other breakage due to cargo pulling in duplicate/incompatible failure crates (0.1.x, 0.2.x)?   One take away for me here is that exact dependencies are a dangerous workaround in other ways.

**Comment by aleksuss** [comment]
Hi @dekellum. You can clone project [exonum](https://github.com/exonum/exonum) and execute `cargo tree --manifest-path=exonum/Cargo.toml` command

**Comment by dekellum** [comment]
Thanks for that @aleksuss, so your case appears to be same via the (older 5.8) dependency from actix → actix-web.  Looks like new active-web 0.7.3 was just released with a fix, which was fast. Hope its not that hard for you to upgrade.
