### ISSUE TITLE
Export a `Result<T, Error>` alias?

### ISSUE THREAD

**Issue by jsgf** [rust-lang-nursery/failure#95]
I find myself putting:
```
pub type Result<T> = std::result::Result<T, Error>;
```
everywhere I'm setting up failure error types. I ended up doing that so much that I created a `failure_ext` crate that just re-exports `failure` and adds a few things, including that.

Should it just be moved to `failure` itself?

**Comment by vitvakatu** [comment]
Why are you using full path `std::result::Result`? It's the part of language prelude, you can use it just like `Result`

**Comment by jsgf** [comment]
```
type Result<T> = Result<T, Error>;
```
doesn't work: "unsupported cyclic reference between types/traits detected"

**Comment by dherman** [comment]
I was going to request this same feature: it's a common idiom to define a `some_crate::Result<T>` as a shorthand for `std::result::Result<T, some_crate::Error>`. I have found this eliminates a large amount of boilerplate and greatly improves readability of my code.

Idiomatically, I would continue to explicitly namespace the `Result` type as `failure::Result` in my code, to avoid ambiguity with the `std` Result type. That is, my code would look like:

```rust
use failure;

// ...

fn foo(/* ... */) -> failure::Result<Foo> { /* ... */ }
```

This ends up much less noisy and more readable than

```rust
fn foo(/* ... */) -> Result<Foo, failure::Error> { /* ... */ }
```

especially when instead of a single identifier, the return type is something bigger like `Option<HashMap<String, Foo>>`, e.g.:

```rust
fn foo(/* ... */) -> Result<Option<HashMap<String, Foo>>, failure::Error> { /* ... */ }
```

versus:

```rust
fn foo(/* ... */) -> failure::Result<Option<HashMap<String, Foo>>> { /* ... */ }
```

**Comment by withoutboats** [comment]
Let's talk about this. I'm currently inclined against adding this alias.

> Idiomatically, I would continue to explicitly namespace the Result type as failure::Result in my code, to avoid ambiguity with the std Result type.

This is definitely how Result aliases are intended to be used, but in my experience it is often not what happens. A user  imports `use failure::*` or `use std::io::*` and suddenly the meaning of `Result` has changed in this module. Especially for new users, this can be baffling.

Even for advanced users, last week Steve and I ran into a very confusing bug because of a Result alias & my failure to practice good hygiene in a derive I wrote: withoutboats/configure#2.

My own opinion is that shadowing the names `Result` and `Error` has been a big mistake. The `Error` and `Result` in `std::io` should be called `IoError` and `IoResult`. Probably even worse is that `fmt` whas a `Result` aliased to `Result<(), fmt::Error>`, so it doesn't even take 1 parameter like all the other `Result` aliases do. My recommendation: you should not name your error type `Error`, and if you want a `Result` alias you should name it something other than `Result`. That way, you can import `Error` from failure without qualifying it.

failure, presuming itself to be the ultimate error handling solution, claims the right to name its error type `Error`. But it can't make the same claim to `Result`, since there needs to be the "base Result" that everyone uses for their results.

I'd be happy to add an alias, then, if we could come up with a name other than `Result`. But I am at a loss to think of what would be better than just `Result<_, Error>`. Is it really preferable to use `FailureResult` or `ErrorResult` or `Fallible`? Do you have any better ideas?

**Comment by Celti** [comment]
Perhaps `AnyResult`, given that it is supposed to coerce any sort of `Result<T, _>` into a `Result<T, failure::Error>`?

**Comment by dherman** [comment]
You make great points, @withoutboats.

> My own opinion is that shadowing the names `Result` and `Error` has been a big mistake.

Yeah, I definitely agree with this. It was a stumbling block for me, too. I remember staring at the docs for `io` APIs and trying to make sense of the fact that `Result` only took one argument.

> Is it really preferable to use `FailureResult` or `ErrorResult`

I agree that `FailureResult` and `ErrorResult` are baffling. :)

> or `Fallible`?

I think `Fallible` is pretty beautiful! The idea of this library is to sort of create a universal adapter representing failure, and so it can be thought of as a general encoding of fallibility. We can even refer in English to "a fallible T" to mean a Result using the failure library whose success value is of type T.

I think it's especially nice that "Fallible" is a bit of unclaimed territory in the "global namespace" of the Rust ecosystem. At least for me it would me I'd be less inclined to explicitly namespace it. Today, I tend to import `failure` and then refer to `Error` as `failure::Error` since "Error" is such a generic name. But this gets really noisy.

Just to get a realistic feel, I took a module from a project I'm working on and did an A/B comparison so we could see how `Fallible` would look in the wild:

https://gist.github.com/dherman/960c27c6eff32b3c3686ebca9956d85e

See what you think!

**Comment by nikomatsakis** [comment]
I always create an alias too, and I generally call it `Fallible`.

**Comment by nikomatsakis** [comment]
(That said, the `E` type in my alias is usually my library's private error type.)

**Comment by alexcrichton** [comment]
I'm super duper late to this, and the time has long since passed for this. That in mind though, this is something I just ran across today (the `Fallible` type alias) and was somewhat surprised it existed with that name! I'd love to use "vanilla `failure`" in Cargo but I'm somewhat resistant to lose the word "result" in the return type of all functions (currently called `CargoResult` for weird historical reasons).

I completely agree though in that `io::Result` and `fmt::Result` are a little odd and I'm not always comfortable with them. That being said, one thing we can do with the 2018 edition is:

```rust
// no extern crate

// ...

// no `use`!

fn foo() -> failure::Result<()> {
}
```

In the 2018 edition no imports are necessary (and no shadowing!). Just food for thought :)
